// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgJNk1Zll2mRIUOZK_53WEjmFdkSlQ0R0',
    appId: '1:468893781226:web:e1e4130838487b19951b93',
    messagingSenderId: '468893781226',
    projectId: 'main-app-e02c5',
    authDomain: 'main-app-e02c5.firebaseapp.com',
    storageBucket: 'main-app-e02c5.firebasestorage.app',
    measurementId: 'G-LMY725NNJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF0SVVS2g0iTSqrgNHx9C4izDwCgX262w',
    appId: '1:468893781226:android:4365583d52ea4354951b93',
    messagingSenderId: '468893781226',
    projectId: 'main-app-e02c5',
    storageBucket: 'main-app-e02c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa8o1A-vVfDrJ44Chr630sY5sD6tZJDIg',
    appId: '1:468893781226:ios:e926061942a94465951b93',
    messagingSenderId: '468893781226',
    projectId: 'main-app-e02c5',
    storageBucket: 'main-app-e02c5.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa8o1A-vVfDrJ44Chr630sY5sD6tZJDIg',
    appId: '1:468893781226:ios:e926061942a94465951b93',
    messagingSenderId: '468893781226',
    projectId: 'main-app-e02c5',
    storageBucket: 'main-app-e02c5.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgJNk1Zll2mRIUOZK_53WEjmFdkSlQ0R0',
    appId: '1:468893781226:web:8824be063e37c9e7951b93',
    messagingSenderId: '468893781226',
    projectId: 'main-app-e02c5',
    authDomain: 'main-app-e02c5.firebaseapp.com',
    storageBucket: 'main-app-e02c5.firebasestorage.app',
    measurementId: 'G-THPVWFJBF5',
  );
}
